### ISSUE TITLE
VGN compatibility

### ISSUE THREAD

**Issue by sophielueth** [ethz-asl/active_grasp#2]
Hello,

I followed your setup instructions and wanted to try the simulation experiment: 
`python3 scripts/run.py nbv`
It causes the following error:
```
Traceback (most recent call last):
  File "src/active_grasp/scripts/run.py", line 10, in <module>
    from active_grasp.controller import *
  File "~/active_grasp_ws/devel/lib/python3/dist-packages/active_grasp/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "~/active_grasp_ws/src/active_grasp/src/active_grasp/policy.py", line 10, in <module>
    from vgn.perception import UniformTSDFVolume
ImportError: cannot import name 'UniformTSDFVolume' from 'vgn.perception'
```

I have all put required external packages (including vgn cloned from [here](https://github.com/ethz-asl/vgn/tree/devel)) into the `active_grasp_ws` and have successfully built and sourced them with catkin. But even in the VGN GitHub directory I can't find a class or type UniformTSDFVolume:

Is this just due to a missing line pointing to `o3d.pipelines.integration.UniformTSDFVolume`? Or have you used a specific version of VGN that you could point out?

Thank you!

**Comment by sophielueth** [comment]
The issue is resolved by using the 'devel' branch of VGN - I accidentally cloned the default one.
